name: "Greet User"
description: "Sends a greeting message"
inputs:
  name:
    description: "User's name"
    required: true
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "node16"
  main: "index.js"
