name: main reusable Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/reusable.yml  # Reference to the reusable workflow

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to production
        run: echo "Deploying to production..."
