name: "Meta Data Syntax Workflow"

on: [push]

jobs:
  greet_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./  # Use the local action
        with:
          name: "Alice"

      - name: Print Greeting
        run: echo "Greeting Message - ${{ steps.greet_job.outputs.message }}"
