name: reusable Workflow

# .github/workflows/reusable-secrets.yml

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
      param2:
        required: true
        type: string
    secrets:
      MY_SECRET_KEY:
        required: true
      MY_SECRET_KEY_1:
        required: true

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use secrets and inputs
        run: echo "param1 is ${{ inputs.param1 }} and param2 is ${{ inputs.param2 }}"
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          MY_SECRET_KEY_1: ${{ secrets.MY_SECRET_KEY_1 }}
