name: Workflow Commands Demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variable
        run: echo "MY_ENV_VAR=Hello GitHub Actions!" >> $GITHUB_ENV

      - name: Set Output Variable
        id: output_step
        run: echo "MY_OUTPUT_VAR=This is an output variable!" >> $GITHUB_OUTPUT

      - name: Mask Secret
        run: echo "::add-mask::SuperSecretPassword"

      - name: Group Logs
        run: |
          echo "::group::Installing Dependencies"
          echo "Installing package 1..."
          echo "Installing package 2..."
          echo "Installing package 3..."
          echo "::endgroup::"

      - name: Debug Message
        run: echo "::debug::This is a debug log message"

      - name: Display Warning notice and Error
        run: |
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"
          echo "::error::This is an error message"

      - name: Fail on Error
        run: |
          echo "::error::Something went wrong!"
          exit 1
        continue-on-error: true

      - name: Add to PATH
        run: echo "/custom/bin" >> $GITHUB_PATH

      - name: Show Environment Variables
        run: env

      - name: Create and Upload Artifact
        run: echo "Hello, this is an artifact!" > sample_artifact.txt

      - name: Upload Artifact (Updated)
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: sample_artifact.txt

      - name: Use Output Variable
        run: echo "The output variable is '${{ steps.output_step.outputs.MY_OUTPUT_VAR }}'"
